// <auto-generated />
namespace SEPGroup4App.ApplicationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InitialApplications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialApplications));
        
        string IMigrationMetadata.Id
        {
            get { return "201411040247378_InitialApplications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
